on: [push]

jobs:
  rocketchat_job:
    runs-on: ubuntu-latest
    name: Push notification to rocket.chat
    steps:
    - name: Push notification to rocket.chat
      id: rc
      uses: jadolg/rocketchat-notification-action@0.0.5
      with:
        channel: channel
        server: server
        message: message
        user: user
        password: password
