name: Test action

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Send plain message
        uses: ./
        with:
          server: ${{ secrets.ROCKETCHAT_SERVER }}
          user: ${{ secrets.ROCKETCHAT_USER }}
          password: ${{ secrets.ROCKETCHAT_PASSWORD }}
          channel: "#test-notifications-akiel"
          message: "Test plain message from ${{ github.repository }}@${{ github.sha }}"
